name: Publish Docker image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
   push_to_registry:
       name: Push Docker image to Docker Hub
       runs-on: ubuntu-latest
       permissions:
         packages: write
         contents: read
         attestations: write
         id-token: write
       steps:
        - name: Check out the repo
          uses: actions/checkout@v4